# Don't check timing across clock boundaries

set_false_path -from [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT1]]
set_false_path -from [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT3]]
set_false_path -from [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins bd_i/evrMMCM/inst/mmcm_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks bd_i/mdm_1/U0/Use_E2.BSCAN_I/Use_E2.BSCANE2_I/DRCK]
set_false_path -from [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks bd_i/mdm_1/U0/Use_E2.BSCAN_I/Use_E2.BSCANE2_I/UPDATE]
set_false_path -from [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks clk20_vcxo]
set_false_path -from [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt0_mgt_i/gtxe2_i/RXOUTCLK]
set_false_path -from [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt0_mgt_i/gtxe2_i/TXOUTCLK]
set_false_path -from [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt1_mgt_i/gtxe2_i/RXOUTCLK]
set_false_path -from [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt2_mgt_i/gtxe2_i/RXOUTCLK]
set_false_path -from [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt3_mgt_i/gtxe2_i/RXOUTCLK]
set_false_path -from [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt4_mgt_i/gtxe2_i/RXOUTCLK]
set_false_path -from [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt5_mgt_i/gtxe2_i/RXOUTCLK]
set_false_path -from [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt6_mgt_i/gtxe2_i/RXOUTCLK]
set_false_path -from [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt7_mgt_i/gtxe2_i/RXOUTCLK]
set_false_path -from [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT1]] -to [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT1]] -to [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt0_mgt_i/gtxe2_i/TXOUTCLK]
set_false_path -from [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT1]] -to [get_clocks rx_clk]
set_false_path -from [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT2]] -to [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins bd_i/evrMMCM/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins bd_i/latencyMMCM/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks FMC1_CLK0_M2C] -to [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks FMC1_CLK1_M2C] -to [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks bd_i/mdm_1/U0/Use_E2.BSCAN_I/Use_E2.BSCANE2_I/DRCK] -to [get_clocks bd_i/mdm_1/U0/Use_E2.BSCAN_I/Use_E2.BSCANE2_I/UPDATE]
set_false_path -from [get_clocks bd_i/mdm_1/U0/Use_E2.BSCAN_I/Use_E2.BSCANE2_I/UPDATE] -to [get_clocks bd_i/mdm_1/U0/Use_E2.BSCAN_I/Use_E2.BSCANE2_I/DRCK]
set_false_path -from [get_clocks clk20_vcxo] -to [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks clk20_vcxo] -to [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT3]]
set_false_path -from [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt0_mgt_i/gtxe2_i/RXOUTCLK] -to [get_clocks clk_out1_bd_clk_wiz_1_0]
set_false_path -from [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt0_mgt_i/gtxe2_i/RXOUTCLK] -to [get_clocks clk_out2_bd_clk_wiz_2_0]
set_false_path -from [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt0_mgt_i/gtxe2_i/TXOUTCLK] -to [get_clocks clk_out1_bd_clk_wiz_1_0]
set_false_path -from [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt0_mgt_i/gtxe2_i/TXOUTCLK] -to [get_clocks clk_out2_bd_clk_wiz_2_0]
set_false_path -from [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt1_mgt_i/gtxe2_i/RXOUTCLK] -to [get_clocks clk_out1_bd_clk_wiz_1_0]
set_false_path -from [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt1_mgt_i/gtxe2_i/RXOUTCLK] -to [get_clocks clk_out2_bd_clk_wiz_2_0]
set_false_path -from [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt2_mgt_i/gtxe2_i/RXOUTCLK] -to [get_clocks clk_out1_bd_clk_wiz_1_0]
set_false_path -from [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt2_mgt_i/gtxe2_i/RXOUTCLK] -to [get_clocks clk_out2_bd_clk_wiz_2_0]
set_false_path -from [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt3_mgt_i/gtxe2_i/RXOUTCLK] -to [get_clocks clk_out1_bd_clk_wiz_1_0]
set_false_path -from [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt3_mgt_i/gtxe2_i/RXOUTCLK] -to [get_clocks clk_out2_bd_clk_wiz_2_0]
set_false_path -from [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt4_mgt_i/gtxe2_i/RXOUTCLK] -to [get_clocks clk_out1_bd_clk_wiz_1_0]
set_false_path -from [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt4_mgt_i/gtxe2_i/RXOUTCLK] -to [get_clocks clk_out2_bd_clk_wiz_2_0]
set_false_path -from [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt5_mgt_i/gtxe2_i/RXOUTCLK] -to [get_clocks clk_out1_bd_clk_wiz_1_0]
set_false_path -from [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt5_mgt_i/gtxe2_i/RXOUTCLK] -to [get_clocks clk_out2_bd_clk_wiz_2_0]
set_false_path -from [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt5_mgt_i/gtxe2_i/RXOUTCLK] -to [get_clocks clk_out4_bd_clk_wiz_1_0]
set_false_path -from [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt5_mgt_i/gtxe2_i/RXOUTCLK] -to [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt0_mgt_i/gtxe2_i/TXOUTCLK]
set_false_path -from [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt6_mgt_i/gtxe2_i/RXOUTCLK] -to [get_clocks clk_out1_bd_clk_wiz_1_0]
set_false_path -from [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt6_mgt_i/gtxe2_i/RXOUTCLK] -to [get_clocks clk_out2_bd_clk_wiz_2_0]
set_false_path -from [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt7_mgt_i/gtxe2_i/RXOUTCLK] -to [get_clocks clk_out1_bd_clk_wiz_1_0]
set_false_path -from [get_clocks fiberLinks/mgtWrapper_i/mgt_i/inst/mgt_i/gt7_mgt_i/gtxe2_i/RXOUTCLK] -to [get_clocks clk_out2_bd_clk_wiz_2_0]
set_false_path -from [get_clocks rx_clk] -to [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT1]]
